### ISSUE TITLE
BBMRI-CS-IT WP4 - Definition of Collection

### ISSUE THREAD

**Issue by DrUrwin** [BBMRI-ERIC/miabis#1]
### **BBMRI-CS-IT**

**WP4 Meeting Notes (08-09-2020):**
•	To define what ‘collection’ is, the semantics thereof.
•	Transfer the email discussion (about ‘collection’) to the MIABIS GitHub webpage.
•	MIABIS GitHub webpage will henceforth ‘record all issues’.

![Collection_types_of](https://user-images.githubusercontent.com/70956694/92481151-cd245c00-f1dd-11ea-825b-c2b28babe36d.jpg)

**Comment by niinae** [comment]
Collection definition is covered at sufficient level in MIABIS Core v3 update. Here we introduce "Collection status" attribute to describe the activity level of the Collection.
https://www.liebertpub.com/doi/full/10.1089/bio.2023.0074
