### ISSUE TITLE
Age units in collection

### ISSUE THREAD

**Issue by holubp** [BBMRI-ERIC/miabis#11]
Age unit on the collection level are defined as a "text list", but it should be actually a text value only - if it was a list with more than one element, it would be ambiguous.
https://github.com/BBMRI-ERIC/miabis/blob/master/Data-describing-Sample-Collection.md

**Comment by Palollo** [comment]
May be it is a list of two items: the unit for the Age Low and the unit for the Age High. 
This way there can be for example the range: [3 months (ageLow), 2 years (ageHigh)].

**Comment by Palollo** [comment]
In this case, clarification in the two documents would be interesting to avoid ambiguity: 
[Data-describing-Sample-Collection.md](https://github.com/BBMRI-ERIC/miabis/blob/master/Data-describing-Sample-Collection.md)
[Data-describing-Study.md](https://github.com/BBMRI-ERIC/miabis/blob/master/Data-describing-Study.md)

**Comment by niinae** [comment]
The data type for Age units are addressed in Core v3, they are now enumerated values. The units are to be used as @Palollo describes above.
