### ISSUE TITLE
Proposal for new collection type - randomized clinical trial

### ISSUE THREAD

**Issue by holubp** [BBMRI-ERIC/miabis#2]
There is a question coming from the BBMRI.nl: 
---
I have a question we got from a large Dutch project: they would like to add quite a lot of collections to the BBMRI-NL catalogue, but most studies have RCT for collection type and they asked if we could add that one as an option. We heard this request before and could do that, but than we have the issues of mapping to the Directory. Thinking about it I was actually surprised RCT is not an option yet since it is very common, so I thought there must be a good reason why this one is not there (yet). Do you have an idea why?
Otherwise, is it an idea to add RCT as an collection type? And if not, do you know what would be a substitute that already exists in the Directory?
---

Can MIABIS group consider to add this collection type to the MIABIS Core?

**Comment by niinae** [comment]
We have added Clinical trial as a value for Sample collection setting (=Collection type) in MIABIS Core v3 update. In the effort to keep the terminology as generic and minimal as possible, we suggest that the umbrella term of Clinical trial is sufficient at this time.
